export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const TOGGLE_ALL_TODO = "TOGGLE_ALL_TODO";
export const TOGGLE_FILTER = "TOGGLE_FILTER";
export const REMUVE_BUTTON = "REMUVE_BUTTON";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
